//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingTemple.CodingCookware.Web.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressHistory
    {
        public int ID { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string City { get; set; }
    
        public virtual Address Address { get; set; }
    }
}
