//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingTemple.CodingCookware.Web.Areas.Admin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ERPEntities : DbContext
    {
        public ERPEntities()
            : base("name=ERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<AddressHistory> AddressHistories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductType> ProductTypes { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
    
        public virtual int sp_AddStoreWithAddress(string street1, string street2, string city, string state, string zip, string storeName)
        {
            var street1Parameter = street1 != null ?
                new ObjectParameter("street1", street1) :
                new ObjectParameter("street1", typeof(string));
    
            var street2Parameter = street2 != null ?
                new ObjectParameter("street2", street2) :
                new ObjectParameter("street2", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var zipParameter = zip != null ?
                new ObjectParameter("zip", zip) :
                new ObjectParameter("zip", typeof(string));
    
            var storeNameParameter = storeName != null ?
                new ObjectParameter("storeName", storeName) :
                new ObjectParameter("storeName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AddStoreWithAddress", street1Parameter, street2Parameter, cityParameter, stateParameter, zipParameter, storeNameParameter);
        }
    
        public virtual ObjectResult<sp_GetEmployeesWorking_Result> sp_GetEmployeesWorking(Nullable<System.DateTime> date, Nullable<int> store)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var storeParameter = store.HasValue ?
                new ObjectParameter("store", store) :
                new ObjectParameter("store", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetEmployeesWorking_Result>("sp_GetEmployeesWorking", dateParameter, storeParameter);
        }
    
        public virtual ObjectResult<sp_GetPurchasesByEmail_Result> sp_GetPurchasesByEmail(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPurchasesByEmail_Result>("sp_GetPurchasesByEmail", emailParameter);
        }
    
        public virtual ObjectResult<sp_GetStoreRevenue_Result> sp_GetStoreRevenue(Nullable<int> store)
        {
            var storeParameter = store.HasValue ?
                new ObjectParameter("store", store) :
                new ObjectParameter("store", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetStoreRevenue_Result>("sp_GetStoreRevenue", storeParameter);
        }
    
        public virtual ObjectResult<sp_GetStores_Result> sp_GetStores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetStores_Result>("sp_GetStores");
        }
    }
}
