CREATE TABLE [dbo].[Basket]
(
	[ID] INT IDENTITY(1,1) NOT NULL, 
    [AspNetUserID] NVARCHAR(128) NULL, 
    [Name] NVARCHAR(100) NULL, 
	[Created] DATETIME NULL DEFAULT GetUtcDate(),
	[Modified] DATETIME NULL DEFAULT GetUtcDate(),
    CONSTRAINT [PK_Basket] PRIMARY KEY ([ID]), 
    CONSTRAINT [FK_Basket_AspNetUsers] FOREIGN KEY (AspNetUserID) REFERENCES AspNetUsers([Id]) ON DELETE SET NULL
)
